// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hslttdusoutrlmodunmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzbHR0ZHVzb3V0cmxtb2R1bm1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMDQ5OTIsImV4cCI6MjA2NDY4MDk5Mn0.CGdSlkKbpf9_zniwndbWWvER8_sP0DCdiDSk7YByAI8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);